telegram:
  bot_token: ${TELEGRAM_BOT_TOKEN}
  chat_id: ${TELEGRAM_CHAT_ID}

sources:

  tailscale:
    enabled: true
    schedule:
      type: interval
      interval: 600
    filters:
      required_matches: 1
      components:
        enabled: true
        values:
          - Admin console (console.tailscale.com)
          - API (api.tailscale.com)
          - Coordination service
          - DERP relay servers
          - Certificates
          - Mullvad exit nodes
          - Homepage and Documentation (tailscale.com)
          - Package server (pkgs.tailscale.com)
          - Funnel
          - Aperture
          - Tailscale Support
          - Tailscale PAM
    message:
      title: true
      status: true
      components: true
      updated_at: true
      link: true

  cloudflare:
    enabled: true
    schedule:
      type: interval
      interval: 600
    filters:
      required_matches: 1
      severity:
        enabled: true
        values:
          - Critical
          - Major
          # - Minor
      components:
        enabled: true
        values:
        # CDN & Performance
          - CDN/Cache
          - Always Online
          - Cache Reserve
          - CDN Cache Purge
          - Cloud Connector
          - Custom Pages
          - Load Balancing and Monitoring
          - Speed Optimizations
          - Waiting Room
          - WebSockets
        # DNS
          - Authoritative DNS
          - DNS Firewall
          - DNS Root Servers
          - DNS Updates
          - Recursive DNS
          - Secondary DNS
        # Network Services
          - Network
          - Argo Smart Routing
          - Bring Your Own IP (BYOIP)
          - Cloud Network Interconnect (CNI)
          - Health Checks
          - Infrastructure
          - IP Geolocation
          - Cloudflare Network Firewall
          - Magic Transit
          - Cloudflare WAN
          - Spectrum
          - Time Services
        # Dashboard & API
          - Dashboard
          - API
          - Account Management
          - Audit Logs
          - Billing
          - Notifications
          - Subscriptions
          - User Profiles
        # Zone Managment
          - Zones
          - Zone Versioning
        # Sites
          - Abuse Reports
          - Blog
          - Community Sites
          - Developer's Site
          - Marketing Site
          - Support Site
        # SSL & TLS
          - SSL Certificate Provisioning
          - SSL for SaaS Provisioning
        # Security
          - API Shield
          - Bot Management
          - Brand Protection
          - Challenge Platform
          - Cloudforce One Reports
          - Firewall
          - Lists
          - Page Shield
          - Precursor
          - Rules
          - Security Center
          - Turnstile
          - URL Scanner
        # AI
          - Workers AI
          - AI Gateway
          - AI Search
          - MCP Portal
          - Replicate
          - Vectorize
        # Developers Services
          - Workers
          - Durable Objects
          - Artifacts
          - Browser Run
          - Containers
          - D1
          - Distributed Web Gateway
          - Ethereum Gateway
          - Hyperdrive
          - Snippets
          - Pages
          - Pipelines
          - Queues
          - R2
          - R2 Data Catalog
          - R2 SQL
          - Randomness Beacon
          - Workers Assets
          - Workers Builds
          - Workers Preview
          - Workers KV
          - Workflows
          - Wrangler
          - Workers VPC
        # Analytics & Observability
          - Analytics
          - Log Explorer
          - Logs
          - Observatory
          - Radar
          - Trace
          - Web Analytics
          - Workers Observability
          - Zaraz
        # Email
          - Email Routing
          - Email Sending
        # Registrar
          - Registrar
          - Registration Data Access Protocol (RDAP)
        # Zero Trust
          - Zero Trust
          - Access
          - Area 1 - API
          - Area 1 - Dash
          - Browser Isolation
          - Cloud Access Security Broker (CASB)
          - Cloud App Control / Kivera
          - Cloudflare One Client
          - Data Loss Prevention (DLP)
          - Digital Experience Monitoring (DEX)
          - Email Security (Area1)
          - Email Security (Zero Trust)
          - Gateway
          - Cloudflare One Appliance
          - Mesh
          - Tunnel
          - WARP
          - Zero Trust Dashboard
        # Media
          - Image Resizing
          - Images
          - Stream
        # Realtime
          - Realtime SFU
          - Realtime TURN Service
          - RealtimeKit
        # Data Localization
          - Data Localization Suite
          - Geo-Key Manager
        # Cloudflare Sites and Services
          - Keyless SSL

    message:
      title: true
      severity: true
      status: true
      components: true
      updated_at: true
      link: true

  scaleway:
    enabled: true
    schedule:
      type: interval
      interval: 600

  artifacthub:
    enabled: true
    schedule:
      type: cron
      cron: "0 7 * * 1" # cron: "12 20 * * *"
      timezone: Europe/Warsaw
    lookback_hours: 168
    statuspulse_url: http://localhost:8000

    repository:
      url: https://github.com/filip-del309/test-cloud-kube-infra.git
      branch: main
      path: ./data/test-cloud-kube-infra
      username: ${GITHUB_USERNAME}
      token: ${GITHUB_TOKEN}

    packages:
      - name: grafana/alloy
        folders:
          - alloy
      - name: argo/argo-cd
        folders: 
          - argo-cd
      - name: argo/argo-events
        folders: 
          - argo-events
      - name: argo/argo-workflows
        folders: 
          - argo-workflows
      - name: argo/argocd-image-updater
        folders: 
          - argocd-image-updater
      - name: atlantis/atlantis
        folders: 
          - atlantis
      - name: aws/aws-load-balancer-controller
        folders: 
          - aws-lb-controller
      - name: backstage/backstage
        folders: 
          - backstage
      - name: bytebase/bytebase
        folders: 
          - bytebase
      - name: cert-manager/cert-manager
        folders: 
          - cert-manager
      - name: external-dns/external-dns
        folders: 
          - external-dns-cloudflare
          - external-dns-route53
      - name: external-secrets-operator/external-secrets
        folders: 
          - external-secrets
      - name: forgejo-helm/forgejo
        folders: 
          - forgejo
      - name: grafana-community/grafana
        folders: 
          - grafana
      - name: grafana-community/grafana-mcp
        folders: 
          - grafana-mcp
      - name: grafana/grafana-operator
        folders: 
          - grafana-operator
      - name: m0nsterrr-homepage/homepage
        folders: 
          - homepage
      - name: ingress-nginx/ingress-nginx
        folders:
          - ingress-nginx-internal
          - ingress-nginx-external
      - name: kafka-ui/kafka-ui
        folders:
          - kafka-ui
      - name: cloudpirates-keycloak/keycloak
        folders:
          - keycloak
      - name: prometheus-community/kube-prometheus-stack
        folders:
          - kube-prometheus-stack
      - name: librechat/librechat
        folders:
          - librechat
      - name: litellm/litellm-helm
        folders:
          - litellm
      - name: grafana-community/loki
        folders:
          - loki
      - name: longhorn/longhorn
        folders:
          - longhorn
      - name: metrics-server/metrics-server
        folders:
          - metrics-server
      - name: nextcloud/nextcloud
        folders:
          - nextcloud
      - name: oauth2-proxy/oauth2-proxy
        folders:
          - oauth2-proxy
      - name: openebs/openebs
        folders:
          - openebs
      - name: ory/hydra
        folders:
          - ory-hydra
      - name: ory/kratos
        folders:
          - ory-kratos
      - name: portainer/portainer
        folders:
          - portainer
      - name: prefect/prefect-server
        folders:
          - prefect-server
      - name: prefect/prefect-worker
        folders:
          - prefect-worker
      - name: redpanda-data/console
        folders:
          - redpanda-console
      - name: stakater/reloader
        folders:
          - reloader
      - name: tailscale/tailscale-operator
        folders:
          - tailscale-operator
      - name: valkey/valkey
        folders:
          - valkey
      - name: vmware-tanzu/velero
        folders:
          - velero
      - name: zabbix-community/zabbix
        folders:
          - zabbix
          - zabbix-agent
